// Generator registry — maps each output artifact to a pure function that turns
// a GenerationContext into file content. Real prose/prompt bodies come from the
// AI agents later; the structured files (JSON/CSS/theme) are already real.

import type {
  GenerationContext,
  GeneratedArtifact,
  OutputFileName,
  DesignTokens,
} from "@/types";

type Generator = (ctx: GenerationContext) => GeneratedArtifact;

// ---- Structured, already-real generators --------------------------------

const projectBrief: Generator = (ctx) => ({
  name: "PROJECT_BRIEF.json",
  mimeType: "application/json",
  content: JSON.stringify({ projectId: ctx.projectId, ...ctx.brief }, null, 2),
});

const designTokens: Generator = (ctx) => ({
  name: "DESIGN_TOKENS.json",
  mimeType: "application/json",
  content: JSON.stringify(ctx.tokens ?? {}, null, 2),
});

const tokensCss: Generator = (ctx) => ({
  name: "tokens.css",
  mimeType: "text/css",
  content: tokensToCss(ctx.tokens),
});

const tailwindTheme: Generator = (ctx) => ({
  name: "tailwind.theme.json",
  mimeType: "application/json",
  content: JSON.stringify(tokensToTailwind(ctx.tokens), null, 2),
});

const previewHtml: Generator = (ctx) => ({
  name: "preview.html",
  mimeType: "text/html",
  content: renderPreview(ctx),
});

const componentPreviewHtml: Generator = (ctx) => ({
  name: "component-preview.html",
  mimeType: "text/html",
  content: renderPreview(ctx, true),
});

// ---- Markdown docs + tool prompts (bodies filled by agents later) --------

const DOC_FILES: OutputFileName[] = [
  "RESEARCH_REPORT.md",
  "WEBSITE_ANALYSIS.md",
  "VISUAL_ANALYSIS.md",
  "BRAND.md",
  "DESIGN.md",
  "CREATIVE.md",
  "UX.md",
  "CONTENT.md",
  "COPY_GUIDE.md",
  "COMPONENTS.md",
  "ANIMATION.md",
  "SEO.md",
  "ACCESSIBILITY.md",
];

const PROMPT_FILES: OutputFileName[] = [
  "PROMPT_CODEX.md",
  "PROMPT_CLAUDE_CODE.md",
  "PROMPT_REPLIT.md",
  "PROMPT_LOVABLE.md",
  "PROMPT_BOLT.md",
  "PROMPT_CURSOR.md",
  "PROMPT_V0.md",
  "PROMPT_WEBFLOW.md",
  "PROMPT_WIX.md",
  "PROMPT_WORDPRESS.md",
];

function docGenerator(name: OutputFileName): Generator {
  return (ctx) => ({
    name,
    mimeType: "text/markdown",
    content:
      `# ${name.replace(/\.md$/, "").replace(/_/g, " ")}\n\n` +
      `> Draft for **${ctx.brief.businessName}**. Prose generated by the AI agents (not yet wired).\n\n` +
      injectedAnalysis(name, ctx),
  });
}

function promptGenerator(name: OutputFileName): Generator {
  const tool = name.replace(/^PROMPT_/, "").replace(/\.md$/, "").replace(/_/g, " ");
  return (ctx) => ({
    name,
    mimeType: "text/markdown",
    content:
      `# ${tool} build prompt\n\n` +
      `Use this prompt in **${tool}** to build ${ctx.brief.businessName}'s site using the generated design system.\n\n` +
      "```\n" +
      `Build a website for ${ctx.brief.businessName}. Apply DESIGN_TOKENS.json exactly — ` +
      `colors, type scale, spacing, and motion. Follow BRAND.md, UX.md, and ACCESSIBILITY.md.\n` +
      "```\n\n_Prompt bodies are elaborated by the AI agents (not yet wired)._\n",
  });
}

// Surface any analysis the pipeline produced into the relevant doc.
function injectedAnalysis(name: OutputFileName, ctx: GenerationContext): string {
  if (name === "RESEARCH_REPORT.md" && ctx.research) return ctx.research;
  if (name === "WEBSITE_ANALYSIS.md" && ctx.websiteAnalysis) return ctx.websiteAnalysis;
  if (name === "VISUAL_ANALYSIS.md" && ctx.visualAnalysis) return ctx.visualAnalysis;
  return "_Section pending._";
}

// ---- Registry -----------------------------------------------------------

export const generators = new Map<OutputFileName, Generator>([
  ["PROJECT_BRIEF.json", projectBrief],
  ["DESIGN_TOKENS.json", designTokens],
  ["tokens.css", tokensCss],
  ["tailwind.theme.json", tailwindTheme],
  ["preview.html", previewHtml],
  ["component-preview.html", componentPreviewHtml],
  ...DOC_FILES.map((n) => [n, docGenerator(n)] as const),
  ...PROMPT_FILES.map((n) => [n, promptGenerator(n)] as const),
]);

/** Run every registered generator for a context. */
export function generateAll(ctx: GenerationContext): GeneratedArtifact[] {
  return [...generators.values()].map((g) => g(ctx));
}

export function generateOne(name: OutputFileName, ctx: GenerationContext): GeneratedArtifact {
  const g = generators.get(name);
  if (!g) throw new Error(`No generator registered for "${name}"`);
  return g(ctx);
}

// ---- Helpers ------------------------------------------------------------

function tokensToCss(tokens?: DesignTokens): string {
  if (!tokens) return ":root {}\n";
  const lines: string[] = [":root {"];
  for (const [k, v] of Object.entries(tokens.color)) lines.push(`  --color-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.typography.scale)) lines.push(`  --text-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.spacing)) lines.push(`  --space-${k}: ${v};`);
  for (const [k, v] of Object.entries(tokens.radius)) lines.push(`  --radius-${k}: ${v};`);
  lines.push("}");
  return lines.join("\n") + "\n";
}

function tokensToTailwind(tokens?: DesignTokens) {
  if (!tokens) return { theme: { extend: {} } };
  return {
    theme: {
      extend: {
        colors: tokens.color,
        spacing: tokens.spacing,
        borderRadius: tokens.radius,
        fontFamily: tokens.typography.fontFamilies,
      },
    },
  };
}

function renderPreview(ctx: GenerationContext, componentsOnly = false): string {
  const t = ctx.tokens;
  const primary = t?.color["brand-500"] ?? "#4F46E5";
  const heading = t?.typography.fontFamilies.display ?? "sans-serif";
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${ctx.brief.businessName} — ${componentsOnly ? "Components" : "Preview"}</title>
<style>
  :root { --primary: ${primary}; }
  body { font-family: ${heading}, system-ui, sans-serif; margin: 0; padding: 3rem; color: #111; }
  .btn { background: var(--primary); color: #fff; padding: .75rem 1.25rem; border-radius: 8px; border: 0; }
</style>
</head>
<body>
  <h1>${ctx.brief.businessName}</h1>
  <p>${componentsOnly ? "Component preview" : "Design system preview"} — generated from DESIGN_TOKENS.json.</p>
  <button class="btn">Primary action</button>
</body>
</html>
`;
}
