// AI agents — the pipeline stages that enrich a GenerationContext before files
// are generated. Real implementations will call the OpenAI API (added later);
// for now each is a deterministic stub so the pipeline is end-to-end wireable.

import type { GenerationContext } from "@/types";

export interface Agent {
  name: string;
  /** Returns a partial context patch to merge into the running context. */
  run(ctx: GenerationContext): Promise<Partial<GenerationContext>>;
}

export const researchAgent: Agent = {
  name: "research",
  async run(ctx) {
    return {
      research: `# Research Report (stub)\n\nBusiness: ${ctx.brief.businessName}\nIndustry: ${ctx.brief.industry ?? "n/a"}\n\n_Real market/competitor research is generated by the OpenAI-backed agent (not yet wired)._`,
    };
  },
};

export const websiteAnalysisAgent: Agent = {
  name: "website-analysis",
  async run() {
    return {
      websiteAnalysis:
        "# Website Analysis (stub)\n\n_Crawled via the Playwright worker; structure, tech, and content analysis go here._",
    };
  },
};

export const visualAnalysisAgent: Agent = {
  name: "visual-analysis",
  async run() {
    return {
      visualAnalysis:
        "# Visual Analysis (stub)\n\n_Screenshot/vision analysis of uploaded assets produces palette, type, and layout observations here._",
    };
  },
};

export const tokenAgent: Agent = {
  name: "design-tokens",
  async run() {
    // Placeholder token set; the real agent synthesizes these from analysis.
    return {
      tokens: {
        color: {
          "brand-500": "#4F46E5",
          "brand-600": "#4338CA",
          "neutral-900": "#111827",
          "neutral-50": "#F9FAFB",
        },
        typography: {
          fontFamilies: { display: "Inter", body: "Inter", mono: "IBM Plex Mono" },
          scale: { h1: "clamp(40px,5vw,72px)", h2: "clamp(28px,3vw,44px)", body: "16px" },
          weights: { regular: 400, medium: 500, bold: 700 },
        },
        spacing: { xs: "4px", sm: "8px", md: "16px", lg: "24px", xl: "40px" },
        radius: { sm: "4px", md: "8px", lg: "16px" },
        shadow: { card: "0 10px 30px -18px rgba(0,0,0,0.4)" },
        motion: { ease: "cubic-bezier(.2,.8,.2,1)", fast: "150ms", base: "300ms" },
      },
    };
  },
};

/** Ordered pipeline. Later stages can read earlier stages' output. */
export const pipeline: Agent[] = [
  researchAgent,
  websiteAnalysisAgent,
  visualAnalysisAgent,
  tokenAgent,
];

export async function runPipeline(ctx: GenerationContext): Promise<GenerationContext> {
  let acc = ctx;
  for (const agent of pipeline) {
    const patch = await agent.run(acc);
    acc = { ...acc, ...patch };
  }
  return acc;
}
